"""How to fix each of our own SAST rules: a minimal before/after example in its language.

The examples illustrate the pattern the rule detects (rules/*.yml) and its usual fix; they are not a
patch for the finding's actual code. Short on purpose: they are read in a side panel and in a PR.
"""

from __future__ import annotations

from pitangus.shared.i18n import msg

# rule_id: (highlight language, before, after, optional note)
EXAMPLES: dict[str, tuple[str, str, str, dict | str]] = {
    # --- Python ---
    "appsec.py.eval-exec-non-literal": ("python", "value = eval(request.args['expr'])",
                                        "import ast\nvalue = ast.literal_eval(request.args['expr'])  # literals only",
                                        msg("findings.fix_examples.py_eval_exec_non_literal")),
    "appsec.py.shell-command-non-literal": ("python", "subprocess.run(f\"convert {name} out.png\", shell=True)",
                                            "subprocess.run([\"convert\", name, \"out.png\"], check=True)  # no shell",
                                            msg("findings.fix_examples.py_shell_command_non_literal")),
    "appsec.py.sql-string-building": ("python", "cursor.execute(f\"SELECT * FROM users WHERE id = {user_id}\")",
                                      "cursor.execute(\"SELECT * FROM users WHERE id = %s\", (user_id,))", ""),
    "appsec.py.sql-injection-from-request": ("python", "db.execute(\"SELECT * FROM t WHERE name = '\" + request.args['q'] + \"'\")",
                                             "db.execute(\"SELECT * FROM t WHERE name = %s\", (request.args['q'],))", ""),
    "appsec.py.ssti-render-template-string": ("python", "return render_template_string(\"Hello \" + name)",
                                              "return render_template(\"hello.html\", name=name)  # fixed template, data as a variable", ""),
    "appsec.py.pickle-load": ("python", "data = pickle.loads(request.data)",
                              "data = json.loads(request.data)  # a data format, not objects",
                              msg("findings.fix_examples.py_pickle_load")),
    "appsec.py.yaml-load-unsafe": ("python", "config = yaml.load(text, Loader=yaml.Loader)", "config = yaml.safe_load(text)", ""),
    "appsec.py.flask-debug-true": ("python", "app.run(debug=True)",
                                   "app.run(debug=os.environ.get(\"FLASK_DEBUG\") == \"1\")  # never in production",
                                   msg("findings.fix_examples.py_flask_debug_true")),
    "appsec.py.requests-verify-false": ("python", "requests.get(url, verify=False)",
                                        "requests.get(url, timeout=10)  # verifies the certificate (the default)",
                                        msg("findings.fix_examples.py_requests_verify_false")),
    "appsec.py.jwt-decode-unverified": ("python", "claims = jwt.decode(token, options={\"verify_signature\": False})",
                                        "claims = jwt.decode(token, key, algorithms=[\"RS256\"], audience=AUDIENCE, issuer=ISSUER)", ""),
    "appsec.py.weak-password-hash": ("python", "digest = hashlib.md5(password.encode()).hexdigest()",
                                     "from argon2 import PasswordHasher\ndigest = PasswordHasher().hash(password)",
                                     msg("findings.fix_examples.py_weak_password_hash")),
    "appsec.py.django-mark-safe-non-literal": ("python", "return mark_safe(f\"<b>{comment}</b>\")",
                                               "return format_html(\"<b>{}</b>\", comment)  # escapes the value", ""),
    "appsec.py.path-traversal-from-request": ("python", "return send_file(os.path.join(BASE, request.args['file']))",
                                              "return send_from_directory(BASE, request.args['file'])  # rejects ../", ""),
    "appsec.py.ssrf-from-request": ("python", "requests.get(request.args['url'])",
                                    "url = request.args['url']\nif urlparse(url).hostname not in ALLOWED_HOSTS:\n    abort(400)\nrequests.get(url, timeout=10, allow_redirects=False)",
                                    msg("findings.fix_examples.py_ssrf_from_request")),
    # --- JavaScript / TypeScript ---
    "appsec.js.eval-non-literal": ("javascript", "const result = eval(req.query.expr)",
                                   "const result = JSON.parse(req.query.data) // data, not code", ""),
    "appsec.js.command-injection": ("javascript", "exec(`git log ${req.query.branch}`)",
                                    "execFile('git', ['log', '--end-of-options', branch]) // no shell; branch can't be an option",
                                    msg("findings.fix_examples.js_command_injection")),
    "appsec.js.sql-injection": ("javascript", "db.query(`SELECT * FROM users WHERE id = ${req.params.id}`)",
                                "db.query('SELECT * FROM users WHERE id = $1', [req.params.id])", ""),
    "appsec.js.dom-xss-sink": ("javascript", "element.innerHTML = location.hash.slice(1)",
                               "element.textContent = location.hash.slice(1)", msg("findings.fix_examples.js_dom_xss_sink")),
    "appsec.js.react-dangerously-set-inner-html": ("javascript", "<div dangerouslySetInnerHTML={{ __html: comment }} />",
                                                   "<div>{comment}</div> // React escapes the text",
                                                   msg("findings.fix_examples.js_react_dangerously_set_inner_html")),
    "appsec.js.path-traversal": ("javascript", "res.sendFile(path.join(BASE, req.query.file))",
                                 "const target = path.resolve(BASE, req.query.file)\nif (!target.startsWith(BASE + path.sep)) return res.sendStatus(400)\nres.sendFile(target)", ""),
    "appsec.js.open-redirect": ("javascript", "res.redirect(req.query.next)",
                                "const next = ALLOWED.has(req.query.next) ? req.query.next : '/'\nres.redirect(next)", ""),
    "appsec.js.jwt-none-algorithm": ("javascript", "jwt.verify(token, key, { algorithms: ['none', 'HS256'] })",
                                     "jwt.verify(token, key, { algorithms: ['RS256'], audience: AUD, issuer: ISS })", ""),
    "appsec.js.jwt-hardcoded-secret": ("javascript", "jwt.sign(payload, 'my-secret')",
                                       "jwt.sign(payload, process.env.JWT_SECRET, { expiresIn: '15m' })",
                                       msg("findings.fix_examples.js_jwt_hardcoded_secret")),
    "appsec.js.tls-reject-unauthorized-false": ("javascript", "https.request({ ...options, rejectUnauthorized: false })",
                                                "https.request({ ...options, ca: fs.readFileSync('ca.pem') }) // validates the certificate", ""),
    "appsec.js.weak-hash": ("javascript", "crypto.createHash('md5').update(password)",
                            "await argon2.hash(password) // passwords\ncrypto.createHash('sha256') // integrity", ""),
    # --- Java ---
    "appsec.java.sql-concatenation": ("java", "stmt.executeQuery(\"SELECT * FROM users WHERE id = \" + id);",
                                      "PreparedStatement ps = conn.prepareStatement(\"SELECT * FROM users WHERE id = ?\");\nps.setString(1, id);", ""),
    "appsec.java.runtime-exec-concatenation": ("java", "Runtime.getRuntime().exec(\"ping \" + host);",
                                               "new ProcessBuilder(\"ping\", \"-c\", \"1\", host).start(); // no shell",
                                               msg("findings.fix_examples.java_runtime_exec_concatenation")),
    "appsec.java.objectinputstream-readobject": ("java", "Object value = new ObjectInputStream(input).readObject();",
                                                 "ObjectInputStream in = new ObjectInputStream(input);\nin.setObjectInputFilter(ObjectInputFilter.Config.createFilter(\"com.acme.dto.*;!*\"));",
                                                 msg("findings.fix_examples.java_objectinputstream_readobject")),
    "appsec.java.xxe-documentbuilder": ("java", "DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();",
                                        "DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();\nfactory.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true);", ""),
    "appsec.java.trust-all-certificates": ("java", "public void checkServerTrusted(X509Certificate[] c, String a) {}",
                                           "// Use the default TrustManager; for an internal CA, load it into your own KeyStore", ""),
    "appsec.java.hostname-verifier-allow-all": ("java", "connection.setHostnameVerifier((host, session) -> true);",
                                                "// Remove the custom HostnameVerifier: the default one checks the hostname", ""),
    "appsec.java.weak-cipher": ("java", "Cipher.getInstance(\"DES/ECB/PKCS5Padding\")", "Cipher.getInstance(\"AES/GCM/NoPadding\")", ""),
    "appsec.java.hardcoded-password": ("java", "String password = \"S3cr3t!\";", "String password = System.getenv(\"DB_PASSWORD\");",
                                       msg("findings.fix_examples.java_hardcoded_password")),
    "appsec.java.spring-csrf-disabled": ("java", "http.csrf(csrf -> csrf.disable());",
                                         "http.csrf(Customizer.withDefaults()); // disable it only for APIs without session cookies", ""),
    # --- C# ---
    "appsec.cs.sql-string-building": ("csharp", "new SqlCommand(\"SELECT * FROM Users WHERE Id = \" + id, conn);",
                                      "var cmd = new SqlCommand(\"SELECT * FROM Users WHERE Id = @id\", conn);\ncmd.Parameters.AddWithValue(\"@id\", id);", ""),
    "appsec.cs.process-start-concatenation": ("csharp", "Process.Start(\"cmd.exe\", \"/c ping \" + host);",
                                              "var info = new ProcessStartInfo(\"ping\") { UseShellExecute = false };\ninfo.ArgumentList.Add(host);\nProcess.Start(info);", ""),
    "appsec.cs.insecure-deserialization": ("csharp", "new BinaryFormatter().Deserialize(stream);",
                                           "JsonSerializer.Deserialize<OrderDto>(stream);", msg("findings.fix_examples.cs_insecure_deserialization")),
    "appsec.cs.certificate-validation-bypass": ("csharp", "handler.ServerCertificateCustomValidationCallback = (m, c, ch, e) => true;",
                                                "// Remove the callback: default validation checks the chain and the hostname", ""),
    "appsec.cs.razor-html-raw-non-literal": ("csharp", "@Html.Raw(Model.Comment)", "@Model.Comment @* Razor escapes the text *@", ""),
    "appsec.cs.weak-hash": ("csharp", "MD5.HashData(Encoding.UTF8.GetBytes(password));",
                            "var hash = new PasswordHasher<User>().HashPassword(user, password);", ""),
    # --- Go ---
    "appsec.go.sql-string-building": ("go", "db.Query(\"SELECT * FROM users WHERE id = \" + id)", "db.Query(\"SELECT * FROM users WHERE id = $1\", id)", ""),
    "appsec.go.shell-command-non-literal": ("go", "exec.Command(\"sh\", \"-c\", \"ping \"+host)", "exec.Command(\"ping\", \"-c\", \"1\", host) // no shell", ""),
    "appsec.go.tls-insecure-skip-verify": ("go", "&tls.Config{InsecureSkipVerify: true}", "&tls.Config{RootCAs: pool, MinVersion: tls.VersionTLS12}", ""),
    "appsec.go.template-html-unescaped": ("go", "template.HTML(userInput)", "userInput // html/template escapes it when rendering", ""),
    "appsec.go.path-traversal-from-request": ("go", "http.ServeFile(w, r, filepath.Join(base, r.URL.Query().Get(\"file\")))",
                                              "root, _ := os.OpenRoot(base) // Go 1.24+: can't escape base\nf, err := root.Open(r.URL.Query().Get(\"file\"))", ""),
    "appsec.go.weak-hash": ("go", "md5.Sum([]byte(password))", "bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)", ""),
    # --- PHP ---
    "appsec.php.sql-injection": ("php", "$db->query(\"SELECT * FROM users WHERE id = \" . $_GET['id']);",
                                 "$stmt = $db->prepare('SELECT * FROM users WHERE id = ?');\n$stmt->execute([$_GET['id']]);", ""),
    "appsec.php.command-injection": ("php", "system('ping ' . $_GET['host']);", "system('ping -c 1 ' . escapeshellarg($host));",
                                     msg("findings.fix_examples.php_command_injection")),
    "appsec.php.eval-non-literal": ("php", "eval($_POST['code']);", "// Remove eval: use a table of allowed operations", ""),
    "appsec.php.unserialize-from-request": ("php", "$data = unserialize($_COOKIE['cart']);", "$data = json_decode($_COOKIE['cart'], true);", ""),
    "appsec.php.file-inclusion-from-request": ("php", "include $_GET['page'] . '.php';",
                                               "$pages = ['home' => 'home.php', 'about' => 'about.php'];\ninclude $pages[$_GET['page']] ?? 'home.php';", ""),
    "appsec.php.reflected-xss": ("php", "echo $_GET['name'];", "echo htmlspecialchars($_GET['name'], ENT_QUOTES, 'UTF-8');", ""),
    # --- Ruby ---
    "appsec.rb.sql-interpolation": ("ruby", "User.where(\"email = '#{params[:email]}'\")", "User.where(email: params[:email])", ""),
    "appsec.rb.command-injection": ("ruby", "system(\"convert #{params[:file]} out.png\")", "system(\"convert\", params[:file], \"out.png\") # no shell", ""),
    "appsec.rb.unsafe-deserialization": ("ruby", "Marshal.load(Base64.decode64(params[:data]))", "JSON.parse(params[:data])", ""),
    "appsec.rb.html-safe-non-literal": ("ruby", "comment.html_safe", "sanitize(comment) # or just <%= comment %>, which escapes", ""),
    "appsec.rb.mass-assignment-permit-all": ("ruby", "User.update(params[:user].permit!)", "User.update(params.require(:user).permit(:name, :email))", ""),
    "appsec.rb.open-redirect": ("ruby", "redirect_to params[:next]", "redirect_to(params[:next].presence_in(ALLOWED_PATHS) || root_path)", ""),
}
