#!/usr/bin/env python3
"""Writes deploy/compose.yaml: Pitangus in one file, for a server or a platform that takes a single compose file
(Coolify, Dokploy, Portainer, Hostinger's Docker manager). Published images, no clone, no build, no Docker socket.

The Caddyfile and the backup script are embedded from docker/caddy/Caddyfile and scripts/backup-service.sh, so they
never drift: `make standalone` regenerates the file and tests/test_packaging.py checks it is current.
Usage: python3 scripts/standalone-compose.py [--check]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "deploy" / "compose.yaml"


def pinned(name: str) -> str:
    """The image a compose file of this repository pins for `name` (postgres, caddy)."""
    for path in ("compose.yaml", "compose.prod.yaml"):
        found = re.search(rf"image: ({name}:[^\s]+@sha256:[0-9a-f]{{64}})", (ROOT / path).read_text())
        if found:
            return found.group(1)
    raise SystemExit(f"no pinned {name} image")


def embedded(path: str, indent: int) -> str:
    text = (ROOT / path).read_text().replace("$", "$$")  # Compose would interpolate it; the file reads it at run time
    return "\n".join((" " * indent + line) if line else "" for line in text.rstrip("\n").split("\n"))


def version() -> str:
    return re.search(r'^VERSION = "([^"]+)"', (ROOT / "pitangus" / "version.py").read_text(), re.M).group(1)


def render() -> str:
    caddy = embedded("docker/caddy/Caddyfile", 6).replace("{$$PITANGUS_DOMAIN}", "{$$PITANGUS_PUBLIC_URL}")
    caddy = caddy.replace("(compose.prod.yaml)", "(deploy/compose.yaml)").replace("for PITANGUS_DOMAIN", "for PITANGUS_PUBLIC_URL")
    return f"""# Pitangus in one file: published images, nothing to clone or build, no Docker socket.
# Generated by scripts/standalone-compose.py from the repository's files: edit those and run `make standalone`.
#
#   1. Put this file on the server, or paste it into Coolify, Dokploy, Portainer or Hostinger's Docker manager.
#   2. Set the variables (a .env next to this file, or the platform's environment screen):
#        PITANGUS_DB_PASSWORD   openssl rand -hex 24
#        PITANGUS_MASTER_KEY    openssl rand -base64 32   (keep a copy apart: it decrypts every stored secret)
#        PITANGUS_PUBLIC_URL    https://pitangus.example.com
#   3. docker compose up -d
#      With your own domain and no proxy in front: docker compose --profile https up -d (Caddy gets the certificate).
#      Scheduled backups into ./backups: add --profile backup.
#   4. The first administrator's code: docker compose exec api python -m pitangus setup-code
#
# The worker runs the analysis engines inside its own image (PITANGUS_ENGINE_RUNNER=local): nothing in this file
# touches the host's Docker. Guide: docs/deploy.md
name: pitangus

x-app: &app
  user: "10001:10001"
  read_only: true
  tmpfs:
    - /tmp:size=256m
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  depends_on:
    postgres:
      condition: service_healthy
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"

x-env: &env
  PITANGUS_DATABASE_URL: "postgresql+psycopg://pitangus:${{PITANGUS_DB_PASSWORD:?set PITANGUS_DB_PASSWORD (openssl rand -hex 24)}}@postgres:5432/pitangus"
  PITANGUS_MASTER_KEY: "${{PITANGUS_MASTER_KEY:?set PITANGUS_MASTER_KEY (openssl rand -base64 32)}}"
  PITANGUS_PUBLIC_URL: "${{PITANGUS_PUBLIC_URL:?set PITANGUS_PUBLIC_URL (https://your-domain)}}"
  PITANGUS_ALLOWED_ORIGINS: "${{PITANGUS_ALLOWED_ORIGINS:-${{PITANGUS_PUBLIC_URL}}}}"
  # The API is reached through a proxy (Caddy below, or the platform's): its X-Forwarded-For is believed.
  PITANGUS_FORWARDED_ALLOW_IPS: "${{PITANGUS_FORWARDED_ALLOW_IPS:-*}}"
  PITANGUS_DEFAULT_LOCALE: "${{PITANGUS_DEFAULT_LOCALE:-en}}"
  PITANGUS_REQUIRE_TOTP: "${{PITANGUS_REQUIRE_TOTP:-admins}}"
  PITANGUS_METRICS_TOKEN: "${{PITANGUS_METRICS_TOKEN:-}}"
  # CI importing SARIF through POST /api/ci/sarif. Empty = off.
  PITANGUS_IMPORT_TOKEN: "${{PITANGUS_IMPORT_TOKEN:-}}"
  PITANGUS_NVD_API_KEY: "${{PITANGUS_NVD_API_KEY:-}}"
  PITANGUS_LOG_FORMAT: "${{PITANGUS_LOG_FORMAT:-text}}"
  # leader: the leader worker runs the periodic tasks. external: a scheduler calls GET /api/cron with this token.
  PITANGUS_PERIODIC: "${{PITANGUS_PERIODIC:-leader}}"
  PITANGUS_CRON_TOKEN: "${{PITANGUS_CRON_TOKEN:-}}"
  PITANGUS_DATA_DIR: /data

services:
  postgres:
    image: {pinned("postgres")}
    environment:
      POSTGRES_USER: pitangus
      POSTGRES_DB: pitangus
      POSTGRES_PASSWORD: "${{PITANGUS_DB_PASSWORD:?set PITANGUS_DB_PASSWORD}}"
    volumes:
      - pitangus-pg:/var/lib/postgresql
    # The entrypoint starts as root to own the data folder, then drops to the postgres user: only what that takes.
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    networks:
      - db
    shm_size: 128mb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pitangus -d pitangus"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    <<: *app
    image: "${{PITANGUS_IMAGE:-ghcr.io/pitangus-dev/pitangus}}:${{PITANGUS_VERSION:-{version()}}}"
    environment:
      <<: *env
      PITANGUS_EMBEDDED_WORKER: "0"
    volumes:
      - pitangus-data:/data
    networks:
      - default
      - db
      - edge
    # This machine only: a proxy (Caddy below, or the platform's) publishes it with HTTPS.
    ports:
      - "${{PITANGUS_PORT:-127.0.0.1:8766}}:8766"
    # Ceilings so a runaway process can't starve the host (and Postgres with it).
    mem_limit: ${{PITANGUS_API_MEMORY:-1g}}
    pids_limit: 256
    healthcheck:
      test: ["CMD", "python", "-c", "import os,sys,urllib.parse as p,urllib.request as r; h=p.urlsplit(os.environ['PITANGUS_ALLOWED_ORIGINS'].split(',')[0].strip()).netloc; sys.exit(0 if r.urlopen(r.Request('http://127.0.0.1:8766/api/health', headers={{'Host': h}}), timeout=4).status == 200 else 1)"]
      interval: 30s
      timeout: 5s
      retries: 3

  worker:
    <<: *app
    image: "${{PITANGUS_IMAGE:-ghcr.io/pitangus-dev/pitangus}}-worker:${{PITANGUS_VERSION:-{version()}}}"
    environment:
      <<: *env
      # Engines write their temporary files (image layers, databases) to disk, not to the small in-memory /tmp.
      TMPDIR: /data/tmp
    volumes:
      - pitangus-data:/data
    networks:
      - default
      - db
    # The engines run inside this container here: it needs more room than the API, still capped.
    mem_limit: ${{PITANGUS_WORKER_MEMORY:-4g}}
    pids_limit: 1024

  caddy:
    image: {pinned("caddy")}
    profiles: [https]
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      PITANGUS_PUBLIC_URL: "${{PITANGUS_PUBLIC_URL:?set PITANGUS_PUBLIC_URL}}"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    # Only the api: PostgreSQL and the worker aren't on this network.
    networks:
      - edge
    depends_on:
      api:
        condition: service_started
    read_only: true
    tmpfs:
      - /tmp:size=16m
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  backup:
    image: {pinned("postgres")}
    profiles: [backup]
    init: true
    user: "10001:10001"
    entrypoint: ["/bin/sh", "/opt/pitangus/backup-service.sh"]
    environment:
      PGHOST: postgres
      PGUSER: pitangus
      PGDATABASE: pitangus
      PGPASSWORD: "${{PITANGUS_DB_PASSWORD:?set PITANGUS_DB_PASSWORD}}"
      BACKUP_INTERVAL_HOURS: "${{PITANGUS_BACKUP_INTERVAL_HOURS:-24}}"
      BACKUP_KEEP_DAYS: "${{PITANGUS_BACKUP_KEEP_DAYS:-14}}"
      BACKUP_AGE_RECIPIENT: "${{PITANGUS_BACKUP_AGE_RECIPIENT:-}}"
    configs:
      - source: backup
        target: /opt/pitangus/backup-service.sh
    volumes:
      - pitangus-data:/source/data:ro
      - ${{PITANGUS_BACKUP_DIR:-./backups}}:/backups
    networks:
      - db
    read_only: true
    tmpfs:
      - /tmp:size=64m
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

configs:
  caddyfile:
    content: |
{caddy}
  backup:
    content: |
{embedded("scripts/backup-service.sh", 6)}

networks:
  # PostgreSQL's only network, with no way out. The api and the worker also sit on `default` for their outbound calls.
  db:
    internal: true
  # Caddy ↔ api only.
  edge: {{}}

volumes:
  pitangus-pg:
  pitangus-data:
  caddy-data:
  caddy-config:
"""


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != content:
            print("deploy/compose.yaml is out of date: run make standalone", file=sys.stderr)
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
